# ESLint Workflow for Fahrrad Kilometer Tracker
# This workflow runs ESLint checks on every commit and reports any linting errors
name: ESLint

on:
  push:
    branches: [main, develop]
    paths:
      - '**/*.js'
      - '**/*.vue'
      - '**/*.mjs'
      - 'eslint.config.js'
      - 'package.json'
      - 'package-lock.json'
  pull_request:
    branches: [main, develop]
    paths:
      - '**/*.js'
      - '**/*.vue'
      - '**/*.mjs'
      - 'eslint.config.js'
      - 'package.json'
      - 'package-lock.json'

jobs:
  eslint:
    runs-on: ubuntu-latest
    name: ESLint Check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
